In [1]:
import pandas as pd

In [2]:
file = 'data/Pharmacy_Data_Challenge_Dataset.xlsx'

FactSales = pd.read_excel(file, sheet_name='FactSales', engine='openpyxl')
dimProduct = pd.read_excel(file, sheet_name='DimProduct', engine='openpyxl')
dimPharmacy = pd.read_excel(file, sheet_name='DimPharmacy', engine='openpyxl')
dimDate = pd.read_excel(file, sheet_name='DimDate', engine='openpyxl')

In [3]:
df_analysis = (
    FactSales
    .merge(dimDate, on='DateKey', how='left')
    .merge(dimPharmacy, on='PharmacyID', how='left', suffixes=('', '_pharmacy'))
    .merge(dimProduct, on='ProductID', how='left', suffixes=('', '_product'))
)
df_analysis.head()

,SalesID,DateKey,PharmacyID,ProductID,UnitsSold,RevenueEUR,CostEUR,MarginEUR,PromoFlag,Date,...,ProductName,Category,Brand,IsGeneric,PackSize,ListPriceEUR,StandardCostEUR,LaunchDate,IsDiscontinued,DiscontinuedDate
0,S0000001,20240101,PH0002,PR0099,5,128.08,87.55,40.53,No,2024-01-01,...,HairEssence Mouthwash Sensitive,Personal Care,HairEssence,No,150 ml,24.63,17.25,2018-12-06,No,NaN
1,S0000002,20240101,PH0004,PR0156,4,51.89,34.32,17.57,No,2024-01-01,...,NatureFit Omega-3 Active,Wellness,NatureFit,No,500 g,16.63,11.87,2021-05-21,No,NaN
2,S0000003,20240101,PH0007,PR0004,20,317.73,199.53,118.20,No,2024-01-01,...,DermaSoft Shampoo Repair,Personal Care,DermaSoft,No,100 ml,15.13,8.83,2018-01-10,No,NaN
3,S0000004,20240101,PH0009,PR0075,6,90.34,67.49,22.85,No,2024-01-01,...,Medica Paracetamol 20 mg,OTC,Medica,No,30 tablets,14.34,11.37,2017-05-26,No,NaN
4,S0000005,20240101,PH0010,PR0154,2,160.21,124.99,35.22,Yes,2024-01-01,...,CareEquip Digital Thermometer Advance,Medical Devices,CareEquip,No,25 strips,91.50,69.26,2025-07-30,No,NaN

In [4]:
df_analysis.shape

(62139, 34)

In [5]:
FactSales.shape

(62139, 9)

In [6]:
df_analysis.info()

<class 'pandas.DataFrame'>
RangeIndex: 62139 entries, 0 to 62138
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SalesID           62139 non-null  str
 1   DateKey           62139 non-null  int64
 2   PharmacyID        62139 non-null  str
 3   ProductID         62139 non-null  str
 4   UnitsSold         62139 non-null  int64
 5   RevenueEUR        62139 non-null  float64
 6   CostEUR           62139 non-null  float64
 7   MarginEUR         62139 non-null  float64
 8   PromoFlag         62139 non-null  str
 9   Date              62139 non-null  datetime64[us]
 10  Year              62139 non-null  int64
 11  Quarter           62139 non-null  int64
 12  MonthNumber       62139 non-null  int64
 13  MonthName         62139 non-null  str
 14  YearMonth         62139 non-null  str
 15  PharmacyName      62139 non-null  str
 16  Country           62139 non-null  str
 17  Region            62139 non-null  str
 18  City              62139 non-null  str
 19  PharmacyType      62139 non-null  str
 20  OpenDate          62139 non-null  str
 21  StoreSizeBand     62139 non-null  str
 22  Latitude          62139 non-null  float64
 23  Longitude         62139 non-null  float64
 24  ProductName       62139 non-null  str
 25  Category          62139 non-null  str
 26  Brand             62139 non-null  str
 27  IsGeneric         62139 non-null  str
 28  PackSize          62139 non-null  str
 29  ListPriceEUR      62139 non-null  float64
 30  StandardCostEUR   62139 non-null  float64
 31  LaunchDate        62139 non-null  str
 32  IsDiscontinued    62139 non-null  str
 33  DiscontinuedDate  5045 non-null   str
dtypes: datetime64[us](1), float64(7), int64(5), str(21)
memory usage: 16.1 MB

In [9]:
df_analysis.describe()

,DateKey,UnitsSold,RevenueEUR,CostEUR,MarginEUR,Date,Year,Quarter,MonthNumber,Latitude,Longitude,ListPriceEUR,StandardCostEUR
count,6.213900e+04,62139.000000,62139.000000,62139.000000,62139.000000,62139,62139.000000,62139.000000,62139.000000,62139.000000,62139.000000,62139.000000,62139.000000
mean,2.024579e+07,7.174126,138.946190,99.982881,38.963309,2025-01-05 21:38:53.664848,2024.512190,2.519641,6.558216,48.120902,8.131152,25.730213,19.507631
min,2.024010e+07,1.000000,1.610000,1.100000,0.440000,2024-01-01 00:00:00,2024.000000,1.000000,1.000000,37.395178,-6.003924,2.060000,1.400000
25%,2.024071e+07,3.000000,55.250000,39.330000,15.140000,2024-07-08 00:00:00,2024.000000,2.000000,4.000000,45.445908,4.392816,10.950000,7.980000
50%,2.025011e+07,6.000000,102.750000,72.220000,28.990000,2025-01-10 00:00:00,2025.000000,3.000000,7.000000,48.850568,6.977880,16.870000,11.610000
75%,2.025071e+07,10.000000,181.350000,128.680000,51.990000,2025-07-09 00:00:00,2025.000000,4.000000,10.000000,51.224739,12.508677,29.150000,21.810000
max,2.025123e+07,25.000000,1036.280000,834.420000,295.310000,2025-12-31 00:00:00,2025.000000,4.000000,12.000000,54.369348,21.030542,111.080000,82.800000
std,5.014700e+03,4.873395,124.574712,93.611370,33.972445,NaN,0.499855,1.114143,3.441730,4.162928,6.222714,23.511095,18.784088

In [10]:
df_analysis.isnull().sum()

SalesID                 0
DateKey                 0
PharmacyID              0
ProductID               0
UnitsSold               0
RevenueEUR              0
CostEUR                 0
MarginEUR               0
PromoFlag               0
Date                    0
Year                    0
Quarter                 0
MonthNumber             0
MonthName               0
YearMonth               0
PharmacyName            0
Country                 0
Region                  0
City                    0
PharmacyType            0
OpenDate                0
StoreSizeBand           0
Latitude                0
Longitude               0
ProductName             0
Category                0
Brand                   0
IsGeneric               0
PackSize                0
ListPriceEUR            0
StandardCostEUR         0
LaunchDate              0
IsDiscontinued          0
DiscontinuedDate    57094
dtype: int64

In [11]:
df_analysis.value_counts('PromoFlag')

PromoFlag
No     54708
Yes     7431
Name: count, dtype: int64

In [12]:
df_analysis.value_counts('Year')

Year
2025    31827
2024    30312
Name: count, dtype: int64

In [13]:
df_analysis.value_counts('MonthName')

MonthName
July         5441
December     5391
May          5352
October      5322
August       5271
January      5216
September    5202
June         5142
March        5120
November     5016
April        4920
February     4746
Name: count, dtype: int64

In [14]:
df_analysis.value_counts('Country')

Country
Germany        10628
France         10187
Italy           9872
Belgium         8280
Poland          6641
Netherlands     6138
Spain           5700
Austria         4693
Name: count, dtype: int64

In [15]:
df_analysis.value_counts('City')

City
Milan         3512
Hamburg       3066
Munich        3013
Lyon          2887
Utrecht       2772
Liège         2632
Naples        2598
Rotterdam     2417
Lille         2384
Frankfurt     2138
Venice        2108
Marseille     2040
Madrid        1973
Bordeaux      1950
Poznań        1824
Brussels      1669
Kraków        1583
Ghent         1500
Gdańsk        1493
Berlin        1477
Barcelona     1410
Bruges        1359
Vienna        1331
St. Pölten    1208
Bilbao        1195
Seville       1122
Antwerp       1120
Rome          1111
Katowice      1033
Salzburg       992
Cologne        934
Paris          926
Warsaw         708
Innsbruck      644
Amsterdam      634
Bologna        543
Graz           518
Arnhem         315
Name: count, dtype: int64

In [16]:
df_analysis.value_counts('PharmacyType')

PharmacyType
Urban       29552
Suburban    22403
Rural       10184
Name: count, dtype: int64

In [17]:
df_analysis.value_counts('Region')

Region
Lombardy                      3512
Hamburg                       3066
Bavaria                       3013
Auvergne-Rhône-Alpes          2887
Utrecht                       2772
Wallonia                      2632
Campania                      2598
South Holland                 2417
Hauts-de-France               2384
Hesse                         2138
Veneto                        2108
Provence-Alpes-Côte d'Azur    2040
Community of Madrid           1973
Nouvelle-Aquitaine            1950
Greater Poland                1824
Brussels-Capital              1669
Lesser Poland                 1583
East Flanders                 1500
Pomeranian                    1493
Berlin                        1477
Catalonia                     1410
West Flanders                 1359
Vienna                        1331
Lower Austria                 1208
Basque Country                1195
Andalusia                     1122
Flanders                      1120
Lazio                         1111
Silesian                      1033
Salzburg                       992
North Rhine-Westphalia         934
Île-de-France                  926
Masovian                       708
Tyrol                          644
North Holland                  634
Emilia-Romagna                 543
Styria                         518
Gelderland                     315
Name: count, dtype: int64

In [18]:
df_analysis.value_counts('StoreSizeBand')

StoreSizeBand
M    28181
L    19781
S    14177
Name: count, dtype: int64

In [19]:
df_analysis.value_counts('ProductName')

ProductName
PainLess Throat Lozenges 20 mg           722
ColdAway Paracetamol 200 mg              679
NutriCore Magnesium Max                  676
DigestEase Nasal Spray 200 mg            654
ZenHealth Probiotic Daily                641
                                        ...
HairEssence Mouthwash Classic             34
DermaSoft Moisturizer Hydra               33
GlucoMeterX Pulse Oximeter Smart          31
HomeCheck Blood Pressure Monitor Home     22
HairEssence Hand Cream Repair             21
Name: count, Length: 203, dtype: int64

In [20]:
df_analysis.value_counts('Category')

Category
OTC                19412
Prescription       13120
Wellness           12483
Personal Care      11073
Medical Devices     6051
Name: count, dtype: int64

In [21]:
df_analysis.value_counts('IsGeneric')

IsGeneric
No     52302
Yes     9837
Name: count, dtype: int64

In [22]:
df_analysis.value_counts('PackSize')

PackSize
100 ml         7352
30 tablets     6334
500 g          3812
10 tablets     3166
50 g           3160
20 tablets     2972
250 g          2955
400 ml         2560
60 capsules    2449
200 ml         2430
1 pen          2304
90 tablets     2298
90 capsules    2195
60 tablets     2165
15 lozenges    2104
1 unit         2079
150 ml         1922
250 ml         1806
25 strips      1751
75 ml          1549
5 pens         1483
50 strips      1404
30 capsules    1072
10 strips       817
Name: count, dtype: int64

In [23]:
df_analysis.value_counts('IsDiscontinued')

IsDiscontinued
No     57094
Yes     5045
Name: count, dtype: int64

In [24]:
df_analysis.value_counts('LaunchDate')

LaunchDate
2018-06-07    702
2018-04-09    630
2022-02-17    623
2020-03-06    604
2024-07-31    544
             ...
2016-09-24     38
2022-12-15     34
2020-02-12     33
2024-06-02     22
2016-02-24     21
Name: count, Length: 213, dtype: int64